/**
 * 错误码定义
 */

/**
 * 错误码分类
 */
export enum ErrorCategory {
  // 业务错误 (1xxx)
  VALIDATION = 'VALIDATION',
  BUSINESS_RULE = 'BUSINESS_RULE',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',

  // 系统错误 (2xxx)
  CONFIGURATION = 'CONFIGURATION',
  NETWORK = 'NETWORK',
  DATABASE = 'DATABASE',
  INTERNAL = 'INTERNAL',

  // GitLab API 错误 (3xxx)
  GITLAB_API = 'GITLAB_API',
  GITLAB_AUTH = 'GITLAB_AUTH',
  GITLAB_RATE_LIMIT = 'GITLAB_RATE_LIMIT',
}

/**
 * 错误码定义
 */
export const ErrorCodes = {
  // 业务错误 (1xxx)
  VALIDATION_INVALID_PARAMS: 'VALIDATION_1001',
  VALIDATION_MISSING_REQUIRED: 'VALIDATION_1002',
  BUSINESS_RULE_VIOLATION: 'BUSINESS_RULE_2001',
  NOT_FOUND_RESOURCE: 'NOT_FOUND_3001',
  NOT_FOUND_PROJECT: 'NOT_FOUND_3002',
  NOT_FOUND_MERGE_REQUEST: 'NOT_FOUND_3003',
  CONFLICT_STATE: 'CONFLICT_4001',

  // 系统错误 (2xxx)
  CONFIGURATION_INVALID: 'CONFIGURATION_5001',
  CONFIGURATION_MISSING: 'CONFIGURATION_5002',
  NETWORK_TIMEOUT: 'NETWORK_6001',
  NETWORK_CONNECTION: 'NETWORK_6002',
  INTERNAL_UNEXPECTED: 'INTERNAL_7001',

  // GitLab API 错误 (3xxx)
  GITLAB_API_ERROR: 'GITLAB_API_8001',
  GITLAB_API_TIMEOUT: 'GITLAB_API_8002',
  GITLAB_AUTH_FAILED: 'GITLAB_AUTH_9001',
  GITLAB_AUTH_EXPIRED: 'GITLAB_AUTH_9002',
  GITLAB_RATE_LIMIT_EXCEEDED: 'GITLAB_RATE_LIMIT_10001',
} as const;

/**
 * 错误码类型
 */
export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];

